name: Auto Deploy Dynamic

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    types:
      - closed

jobs:
  deploy:
    if: github.event.pull_request.merged == true || github.event_name == 'push'
    runs-on: [self-hosted, main]
    

    steps:
      - name: Show current branch
        run: echo "Current branch is ${{ github.ref_name }}"

      - name: Pull latest code
        run: |
          BRANCH=${{ github.ref_name }}
          cd /home/estudiante/FRONT/planifika-ui
          git fetch origin $BRANCH
          git reset --hard origin/$BRANCH

      - name: Rebuild containers
        run: |
          BRANCH=${{ github.ref_name }}
          cd /home/estudiante/FRONT
          docker compose up -d --build planifika
